"""Add stripe_customer_id to firm_subscriptions

Revision ID: 88fc07bccca3
Revises: b142d20d3335
Create Date: 2025-12-27 17:25:09.476275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fc07bccca3'
down_revision = 'b142d20d3335'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cached_contract_matches_id'), 'cached_contract_matches', ['id'], unique=False)
    op.create_index(op.f('ix_firm_subscriptions_firm_id'), 'firm_subscriptions', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_subscriptions_firm_id'), table_name='firm_subscriptions')
    op.drop_index(op.f('ix_cached_contract_matches_id'), table_name='cached_contract_matches')
    # ### end Alembic commands ###
