"""Add US federal contract fields to company profiles

Revision ID: 8ea68ab7395c
Revises: f71a60d1b71c
Create Date: 2025-11-23 08:51:10.583537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ea68ab7395c'
down_revision = 'f71a60d1b71c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_capabilities_qdrant_id'), table_name='company_capabilities')
    op.create_index(op.f('ix_company_capabilities_qdrant_id'), 'company_capabilities', ['qdrant_id'], unique=False)
    op.alter_column('saved_contracts', 'status',
               existing_type=postgresql.ENUM('interested', 'bidding', 'won', 'lost', name='contractstatus'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'interested'::contractstatus"))
    op.alter_column('saved_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_saved_contracts_firm_id'), table_name='saved_contracts')
    op.drop_index(op.f('idx_saved_contracts_notice_id'), table_name='saved_contracts')
    op.drop_index(op.f('idx_saved_contracts_user_email'), table_name='saved_contracts')
    op.create_index(op.f('ix_saved_contracts_firm_id'), 'saved_contracts', ['firm_id'], unique=False)
    op.create_index(op.f('ix_saved_contracts_id'), 'saved_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_saved_contracts_notice_id'), 'saved_contracts', ['notice_id'], unique=False)
    op.create_index(op.f('ix_saved_contracts_user_email'), 'saved_contracts', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_contracts_user_email'), table_name='saved_contracts')
    op.drop_index(op.f('ix_saved_contracts_notice_id'), table_name='saved_contracts')
    op.drop_index(op.f('ix_saved_contracts_id'), table_name='saved_contracts')
    op.drop_index(op.f('ix_saved_contracts_firm_id'), table_name='saved_contracts')
    op.create_index(op.f('idx_saved_contracts_user_email'), 'saved_contracts', ['user_email'], unique=False)
    op.create_index(op.f('idx_saved_contracts_notice_id'), 'saved_contracts', ['notice_id'], unique=False)
    op.create_index(op.f('idx_saved_contracts_firm_id'), 'saved_contracts', ['firm_id'], unique=False)
    op.alter_column('saved_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_contracts', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('interested', 'bidding', 'won', 'lost', name='contractstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'interested'::contractstatus"))
    op.drop_index(op.f('ix_company_capabilities_qdrant_id'), table_name='company_capabilities')
    op.create_index(op.f('idx_capabilities_qdrant_id'), 'company_capabilities', ['qdrant_id'], unique=False)
    # ### end Alembic commands ###
