"""add US federal fields to company profiles

Revision ID: f71a60d1b71c
Revises: 
Create Date: 2025-11-20 10:19:39.141437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f71a60d1b71c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Capability fields
    op.add_column('company_capabilities', sa.Column('naics_code', sa.String(length=10), nullable=True))
    op.add_column('company_capabilities', sa.Column('security_clearance', sa.String(length=50), nullable=True))
    
    # Company profile - certifications
    op.add_column('company_profiles', sa.Column('sba_certified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('company_profiles', sa.Column('sdvosb_certified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('company_profiles', sa.Column('wosb_certified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('company_profiles', sa.Column('hubzone_certified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('company_profiles', sa.Column('eight_a_certified', sa.Boolean(), nullable=False, server_default='false'))
    
    # Company profile - codes
    op.add_column('company_profiles', sa.Column('naics_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('company_profiles', sa.Column('psc_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    
    # Company profile - identifiers
    op.add_column('company_profiles', sa.Column('cage_code', sa.String(length=50), nullable=True))
    op.add_column('company_profiles', sa.Column('uei_number', sa.String(length=50), nullable=True))
    op.add_column('company_profiles', sa.Column('sam_registered', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('company_profiles', sa.Column('sam_expiration', sa.Date(), nullable=True))
    
    # Company profile - experience
    op.add_column('company_profiles', sa.Column('federal_experience', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('company_profiles', sa.Column('federal_contracts_count', sa.Integer(), nullable=True, server_default='0'))
    
    # Past wins
    op.add_column('past_wins', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.add_column('past_wins', sa.Column('naics_code', sa.String(length=10), nullable=True))
    op.add_column('past_wins', sa.Column('federal_contract', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('past_wins', sa.Column('agency_name', sa.String(length=255), nullable=True))
    
    # Search preferences
    op.add_column('search_preferences', sa.Column('preferred_agencies', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('preferred_set_asides', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('excluded_naics', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    
    # The rest will be auto-generated changes for indexes...

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_preferences', 'excluded_naics')
    op.drop_column('search_preferences', 'preferred_set_asides')
    op.drop_column('search_preferences', 'preferred_agencies')
    op.drop_index(op.f('ix_saved_contracts_user_email'), table_name='saved_contracts')
    op.drop_index(op.f('ix_saved_contracts_notice_id'), table_name='saved_contracts')
    op.drop_index(op.f('ix_saved_contracts_id'), table_name='saved_contracts')
    op.drop_index(op.f('ix_saved_contracts_firm_id'), table_name='saved_contracts')
    op.create_index(op.f('idx_saved_contracts_user_email'), 'saved_contracts', ['user_email'], unique=False)
    op.create_index(op.f('idx_saved_contracts_notice_id'), 'saved_contracts', ['notice_id'], unique=False)
    op.create_index(op.f('idx_saved_contracts_firm_id'), 'saved_contracts', ['firm_id'], unique=False)
    op.alter_column('saved_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_contracts', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('interested', 'bidding', 'won', 'lost', name='contractstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'interested'::contractstatus"))
    op.drop_column('past_wins', 'agency_name')
    op.drop_column('past_wins', 'federal_contract')
    op.drop_column('past_wins', 'naics_code')
    op.drop_column('past_wins', 'contract_number')
    op.drop_column('company_profiles', 'federal_contracts_count')
    op.drop_column('company_profiles', 'federal_experience')
    op.drop_column('company_profiles', 'sam_expiration')
    op.drop_column('company_profiles', 'sam_registered')
    op.drop_column('company_profiles', 'uei_number')
    op.drop_column('company_profiles', 'cage_code')
    op.drop_column('company_profiles', 'psc_codes')
    op.drop_column('company_profiles', 'naics_codes')
    op.drop_column('company_profiles', 'eight_a_certified')
    op.drop_column('company_profiles', 'hubzone_certified')
    op.drop_column('company_profiles', 'wosb_certified')
    op.drop_column('company_profiles', 'sdvosb_certified')
    op.drop_column('company_profiles', 'sba_certified')
    op.drop_index(op.f('ix_company_capabilities_qdrant_id'), table_name='company_capabilities')
    op.create_index(op.f('idx_capabilities_qdrant_id'), 'company_capabilities', ['qdrant_id'], unique=False)
    op.drop_column('company_capabilities', 'security_clearance')
    op.drop_column('company_capabilities', 'naics_code')
    # ### end Alembic commands ###
